In [1]:
#importações e configurações iniciais
import pandas as pd

pd.set_option('display.max_columns', None)

In [3]:
# Votação 2018 - Candidatos por Município e Zona Eleitoral
caminho_arquivo = "../data/parsed_tse/parsed_presidencia_2018.csv"

# Lendo o CSV com os parâmetros corretos para o arquivo do TSE
df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin-1')

# Exibindo as 5 primeiras linhas do dataframe
df.head()

,NR_TURNO,SG_UF,NM_URNA_CANDIDATO,SG_PARTIDO,NM_PARTIDO,QT_VOTOS_NOMINAIS,DS_SIT_TOT_TURNO
0,2,RS,FERNANDO HADDAD,PT,Partido dos Trabalhadores,1094,NÃO ELEITO
1,2,RS,FERNANDO HADDAD,PT,Partido dos Trabalhadores,796,NÃO ELEITO
2,2,RS,FERNANDO HADDAD,PT,Partido dos Trabalhadores,3662,NÃO ELEITO
3,2,RS,FERNANDO HADDAD,PT,Partido dos Trabalhadores,5855,NÃO ELEITO
4,2,RS,FERNANDO HADDAD,PT,Partido dos Trabalhadores,3454,NÃO ELEITO

In [5]:
# Votação 2018 - Candidatos por Município e Zona Eleitoral
caminho_arquivo = "../data/raw/votacao_candidato_munzona_2018_BR.csv"

# Lendo o CSV com os parâmetros corretos para o arquivo do TSE
df2 = pd.read_csv(caminho_arquivo, sep=';', encoding='latin-1')

# Exibindo as 5 primeiras linhas do dataframe
df2.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,CD_SITUACAO_JULGAMENTO,DS_SITUACAO_JULGAMENTO,CD_SITUACAO_CASSACAO,DS_SITUACAO_CASSACAO,CD_SITUACAO_DIPLOMA,DS_SITUACAO_DIPLOMA,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,NR_FEDERACAO,NM_FEDERACAO,SG_FEDERACAO,DS_COMPOSICAO_FEDERACAO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,ST_VOTO_EM_TRANSITO,QT_VOTOS_NOMINAIS,NM_TIPO_DESTINACAO_VOTOS,QT_VOTOS_NOMINAIS_VALIDOS,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO
0,13/11/2024,10:56:11,2018,2,Eleição Ordinária,2,296,ELEIÇÃO GERAL FEDERAL 2018,28/10/2018,F,RS,BR,BRASIL,89141,CAPÃO DO CIPÓ,44,1,Presidente,280000629808,13,FERNANDO HADDAD,FERNANDO HADDAD,#NULO#,12,APTO,2,DEFERIDO,-3,#NE,-3,#NE,-3,#NE,COLIGAÇÃO,13,PT,Partido dos Trabalhadores,-1,#NULO#,#NULO#,#NULO#,280000050703,O POVO FELIZ DE NOVO,PT / PC do B / PROS,N,1094,Válido,1094,4,NÃO ELEITO
1,13/11/2024,10:56:11,2018,2,Eleição Ordinária,2,296,ELEIÇÃO GERAL FEDERAL 2018,28/10/2018,F,RS,BR,BRASIL,85707,SEDE NOVA,91,1,Presidente,280000629808,13,FERNANDO HADDAD,FERNANDO HADDAD,#NULO#,12,APTO,2,DEFERIDO,-3,#NE,-3,#NE,-3,#NE,COLIGAÇÃO,13,PT,Partido dos Trabalhadores,-1,#NULO#,#NULO#,#NULO#,280000050703,O POVO FELIZ DE NOVO,PT / PC do B / PROS,N,796,Válido,796,4,NÃO ELEITO
2,13/11/2024,10:56:11,2018,2,Eleição Ordinária,2,296,ELEIÇÃO GERAL FEDERAL 2018,28/10/2018,F,RS,BR,BRASIL,88935,SÃO SEBASTIÃO DO CAÍ,11,1,Presidente,280000629808,13,FERNANDO HADDAD,FERNANDO HADDAD,#NULO#,12,APTO,2,DEFERIDO,-3,#NE,-3,#NE,-3,#NE,COLIGAÇÃO,13,PT,Partido dos Trabalhadores,-1,#NULO#,#NULO#,#NULO#,280000050703,O POVO FELIZ DE NOVO,PT / PC do B / PROS,N,3662,Válido,3662,4,NÃO ELEITO
3,13/11/2024,10:56:11,2018,2,Eleição Ordinária,2,296,ELEIÇÃO GERAL FEDERAL 2018,28/10/2018,F,RS,BR,BRASIL,87378,MARAU,62,1,Presidente,280000629808,13,FERNANDO HADDAD,FERNANDO HADDAD,#NULO#,12,APTO,2,DEFERIDO,-3,#NE,-3,#NE,-3,#NE,COLIGAÇÃO,13,PT,Partido dos Trabalhadores,-1,#NULO#,#NULO#,#NULO#,280000050703,O POVO FELIZ DE NOVO,PT / PC do B / PROS,N,5855,Válido,5855,4,NÃO ELEITO
4,13/11/2024,10:56:11,2018,2,Eleição Ordinária,2,296,ELEIÇÃO GERAL FEDERAL 2018,28/10/2018,F,RS,BR,BRASIL,86010,CERRO LARGO,96,1,Presidente,280000629808,13,FERNANDO HADDAD,FERNANDO HADDAD,#NULO#,12,APTO,2,DEFERIDO,-3,#NE,-3,#NE,-3,#NE,COLIGAÇÃO,13,PT,Partido dos Trabalhadores,-1,#NULO#,#NULO#,#NULO#,280000050703,O POVO FELIZ DE NOVO,PT / PC do B / PROS,N,3454,Válido,3454,4,NÃO ELEITO

In [ ]:
# TABELA 1: Votos nominais por candidato no 1º turno
turno = 1

tabela = (
    df[df["NR_TURNO"] == turno]
    .groupby("NM_URNA_CANDIDATO", as_index=False)["QT_VOTOS_NOMINAIS"]
    .sum()
    .sort_values("QT_VOTOS_NOMINAIS", ascending=False)
)

# adiciona linha de soma
tabela.loc[len(tabela)] = {
    "NM_URNA_CANDIDATO": "SOMA",
    "QT_VOTOS_NOMINAIS": tabela["QT_VOTOS_NOMINAIS"].sum()
}

tabela

     NM_URNA_CANDIDATO  QT_VOTOS_NOMINAIS
8       JAIR BOLSONARO           48927725
4      FERNANDO HADDAD           30977929
2           CIRO GOMES           13085048
5      GERALDO ALCKMIN            4807844
9          JOÃO AMOÊDO            2509562
1         CABO DACIOLO            1238805
7   HENRIQUE MEIRELLES            1127892
11        MARINA SILVA             963621
0          ALVARO DIAS             739699
6     GUILHERME BOULOS             534149
12                VERA              30753
3               EYMAEL              18188
10  JOÃO GOULART FILHO              12478
13                SOMA          104973693

In [12]:
# TABELA 2: Votos nominais por candidato no 2º turno
turno = 2

tabela = (
    df[df["NR_TURNO"] == turno]
    .groupby("NM_URNA_CANDIDATO", as_index=False)["QT_VOTOS_NOMINAIS"]
    .sum()
    .sort_values("QT_VOTOS_NOMINAIS", ascending=False)
)

# adiciona linha de soma
tabela.loc[len(tabela)] = {
    "NM_URNA_CANDIDATO": "SOMA",
    "QT_VOTOS_NOMINAIS": tabela["QT_VOTOS_NOMINAIS"].sum()
}

tabela

  NM_URNA_CANDIDATO  QT_VOTOS_NOMINAIS
1    JAIR BOLSONARO           57473555
0   FERNANDO HADDAD           46702363
2              SOMA          104175918

In [15]:
# TABELA 3: Votos nominais por candidato no 1º turno, por estado
turno = 1

tabela = (
        df[df["NR_TURNO"] == turno]
        .pivot_table(
            index="SG_UF",
            columns="NM_URNA_CANDIDATO",
            values="QT_VOTOS_NOMINAIS",
            aggfunc="sum",
            fill_value=0
        )
        .sort_index()
)

# Soma de votos por estado
tabela["SOMA"] = tabela.sum(axis=1)

# Total nacional por candidato
tabela.loc["QT"] = tabela.sum()

tabela

NM_URNA_CANDIDATO,ALVARO DIAS,CABO DACIOLO,CIRO GOMES,EYMAEL,FERNANDO HADDAD,GERALDO ALCKMIN,GUILHERME BOULOS,HENRIQUE MEIRELLES,JAIR BOLSONARO,JOÃO AMOÊDO,JOÃO GOULART FILHO,MARINA SILVA,VERA,SOMA
SG_UF,,,,,,,,,,,,,,
AC,1459,3436,21809,209,78170,33115,1602,6283,262508,1969,87,10557,59,421263
AL,4221,17792,154869,243,687247,56892,7827,41990,527683,10618,247,14752,487,1524868
AM,8200,30864,137502,807,746998,28441,10605,22654,805902,26648,178,27987,563,1847349
AP,1417,8882,50553,238,134287,19241,5432,5611,166935,7490,70,8870,555,409581
BA,14024,124812,672430,579,4405111,150555,23193,24559,1700706,36814,807,50255,699,7204544
CE,6456,50129,1995246,644,1608900,48655,12704,22447,1026967,20788,384,15792,678,4809790
DF,11138,26925,266272,744,190508,53640,13177,26939,936494,44879,628,32115,764,1604223
ES,10253,41337,194147,492,495868,77828,7316,21232,1122131,43706,337,25543,376,2040566
GO,13153,29400,272873,566,701349,137614,11528,85630,1860967,65464,179,25779,480,3204982
MA,4618,29806,273810,393,2055819,44353,13484,46523,813493,15269,196,20500,1976,3320240
MG,30663,88631,1203586,1037,2919905,419260,37876,82655,5172872,376362,624,77746,3010,10414227
MS,11482,13839,111530,192,331954,90120,5653,17325,769116,25864,198,11737,424,1389434
MT,11730,11545,88643,362,403101,64895,5750,14890,980427,24755,144,11404,388,1618034
PA,10934,49069,414999,862,1714822,224437,30103,95724,1499294,26967,426,51676,1788,4121101
PB,4235,20694,354298,282,976454,46350,4961,17346,669337,14499,239,10613,389,2119697
PE,7476,90364,633939,421,2304066,73821,18679,26677,1440456,42800,348,42601,898,4682546
PI,3938,9263,202942,370,1158896,42754,4707,12280,336673,13010,94,11077,503,1796507
PR,300523,33431,490248,697,1186716,202821,21113,62995,3469107,177281,978,40312,1041,5987263
RJ,33590,207153,1292446,1917,1244500,200884,51506,69934,5107735,137209,929,126799,3089,8477691
RN,3604,18400,390309,287,732403,37799,5989,9406,536493,14124,249,9294,727,1759084
RO,8265,9653,52118,195,176107,36261,5153,12400,538311,15993,86,6842,344,861728
RR,1464,2833,14838,107,49406,19231,2443,3426,174306,4282,63,4098,132,276629
RS,34832,30279,698518,420,1423364,322962,35621,104707,3319056,170367,1586,43203,1786,6186701
SC,44225,19364,255227,232,574164,145000,17961,42754,2594254,152566,420,22872,829,3869868
SE,3959,13429,147698,131,567991,45166,7298,7980,309844,8654,513,15318,2826,1130807
SP,149789,251436,2615988,5524,3782070,2160724,169415,238804,12336886,1012147,2335,235731,5648,22966497
TO,1771,5104,50638,128,309381,18663,2083,4106,336768,6299,67,5885,120,741013
ZZ,2280,935,27572,109,18372,6362,970,615,113004,12738,66,4263,174,187460
QT,739699,1238805,13085048,18188,30977929,4807844,534149,1127892,48927725,2509562,12478,963621,30753,104973693

In [16]:
# TABELA 3: Votos nominais por candidato no 2º turno, por estado
turno = 2

tabela = (
        df[df["NR_TURNO"] == turno]
        .pivot_table(
            index="SG_UF",
            columns="NM_URNA_CANDIDATO",
            values="QT_VOTOS_NOMINAIS",
            aggfunc="sum",
            fill_value=0
        )
        .sort_index()
)

# Soma de votos por estado
tabela["SOMA"] = tabela.sum(axis=1)

# Total nacional por candidato
tabela.loc["QT"] = tabela.sum()

tabela

NM_URNA_CANDIDATO  FERNANDO HADDAD  JAIR BOLSONARO       SOMA
SG_UF
AC                           86977          294899     381876
AL                          912034          609719    1521753
AM                          875845          883570    1759415
AP                          183616          185096     368712
BA                         5460031         2024193    7484224
CE                         3407526         1382713    4790239
DF                          463340         1080411    1543751
ES                          745263         1271637    2016900
GO                         1107938         2114919    3222857
MA                         2417299          881899    3299198
MG                         4256642         6026286   10282928
MS                          465025          872049    1337074
MT                          549001         1081798    1630799
PA                         2112769         1742188    3854957
PB                         1437714          774853    2212567
PE                         3287681         1659469    4947150
PI                         1392506          416472    1808978
PR                         1915554         4207889    6123443
RJ                         2673386         5669059    8342445
RN                         1121431          646274    1767705
RO                          229343          594968     824311
RR                           72872          183268     256140
RS                         2242942         3860598    6103540
SC                          927531         2959559    3887090
SE                          759061          363276    1122337
SP                         7175836        15204632   22380468
TO                          370262          353229     723491
ZZ                           52938          128632     181570
QT                        46702363        57473555  104175918

In [17]:
# candidatos do segundo turno
candidatos_2t = (
    df.loc[df["NR_TURNO"] == 2, "NM_URNA_CANDIDATO"]
      .unique()
)

comparacao = (
    df[df["NM_URNA_CANDIDATO"].isin(candidatos_2t)]
    .groupby(["NM_URNA_CANDIDATO", "NR_TURNO"])["QT_VOTOS_NOMINAIS"]
    .sum()
    .unstack(fill_value=0)
)

comparacao.columns = ["QT_VOTOS_1T", "QT_VOTOS_2T"]

comparacao["DIFERENCA"] = (
    comparacao["QT_VOTOS_2T"] -
    comparacao["QT_VOTOS_1T"]
)

comparacao = (
    comparacao
    .reset_index()
    .sort_values("QT_VOTOS_2T", ascending=False)
)

comparacao

  NM_URNA_CANDIDATO  QT_VOTOS_1T  QT_VOTOS_2T  DIFERENCA
1    JAIR BOLSONARO     48927725     57473555    8545830
0   FERNANDO HADDAD     30977929     46702363   15724434